In [ ]:
## convert to function
from imutils import contours
from skimage import measure
import numpy as np
import imutils
import cv2
from google.colab.patches import cv2_imshow
import pandas as pd
import glob
from tqdm.auto import tqdm
tqdm.pandas()
import shutil

/usr/local/lib/python3.7/dist-packages/tqdm/std.py:658: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel


In [ ]:

def get_disk(image):
  try:  
    image = cv2.imread(image)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.bilateralFilter(gray,9,75,75)
    median=cv2.medianBlur(blur, 5)

    # threshold the image to reveal light regions in the
    # blurred image
    thresh = cv2.threshold(median, 155, 255, cv2.THRESH_BINARY)[1]
    # perform a series of erosions and dilations to remove
    # any small blobs of noise from the thresholded image
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=4)

    # perform a connected component analysis on the thresholded
    # image, then initialize a mask to store only the "large"
    # components
    labels = measure.label(thresh, connectivity=2, background=0)
    mask = np.zeros(thresh.shape, dtype="uint8")

    # loop over the unique components
    for label in np.unique(labels):
      # if this is the background label, ignore it
      if label == 0:
        continue

      # otherwise, construct the label mask and count the
      # number of pixels 
      labelMask = np.zeros(thresh.shape, dtype="uint8")
      labelMask[labels == label] = 255
      numPixels = cv2.countNonZero(labelMask)

      # if the number of pixels in the component is sufficiently
      # large, then add it to our mask of "large blobs"
      if numPixels >500:
        mask = cv2.add(mask, labelMask)

    # find the contours in the mask, then sort them from left to
    # right
    cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
      cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    cnts = contours.sort_contours(cnts)[0]
    # print (cnts)
    # loop over the contours
    for (i, c) in enumerate(cnts):
        ellipse = cv2.fitEllipse(c)
        (x, y, w, h) = cv2.boundingRect(c)
        break
      # draw the bright spot on the image

    padding = 100
    image = image[y-padding:y+h+padding, x-padding:x+w+padding]
    return True
  except:
    return False

In [ ]:
df = pd.DataFrame(columns=["path", "raises_exception"])

In [ ]:
path_list = (glob.glob("/content/drive/MyDrive/ocular/0/*.*")) + (glob.glob("/content/drive/MyDrive/ocular/1/*.*"))

In [ ]:
df['path'] = path_list

In [ ]:
df['raises_exception'] = df.path.progress_apply(get_disk)

In [ ]:
df.to_csv('exceptions.csv', index=False)

In [ ]:
df

path  raises_exception
0     /content/drive/MyDrive/ocular/0/2569_left.jpg              True
1     /content/drive/MyDrive/ocular/0/2570_left.jpg              True
2     /content/drive/MyDrive/ocular/0/2571_left.jpg             False
3     /content/drive/MyDrive/ocular/0/2572_left.jpg              True
4     /content/drive/MyDrive/ocular/0/2573_left.jpg              True
...                                             ...               ...
3419  /content/drive/MyDrive/ocular/1/2020_left.jpg              True
3420  /content/drive/MyDrive/ocular/1/2030_left.jpg              True
3421  /content/drive/MyDrive/ocular/1/2041_left.jpg              True
3422  /content/drive/MyDrive/ocular/1/2063_left.jpg             False
3423  /content/drive/MyDrive/ocular/1/2074_left.jpg              True

[3424 rows x 2 columns]

In [ ]:
def move_files(from_):
    to_ = "/content/drive/MyDrive/ocular_clean/" + '/'.join(from_.split('/')[-2:-1])
    shutil.copy(from_, to_)

In [ ]:
to_ = "/content/drive/MyDrive/ocular_clean/" + '/'.join(from_.split('/')[-2:-1])

In [ ]:
to_

'/content/gdrive/MyDrive/ocular_clean/0'

In [ ]:
df_clean = df[df.raises_exception]

In [ ]:
df_clean.path.progress_apply(move_files)

0       None
1       None
3       None
4       None
5       None
        ... 
3418    None
3419    None
3420    None
3421    None
3423    None
Name: path, Length: 3042, dtype: object

In [ ]:
df_clean

path  raises_exception
0     /content/drive/MyDrive/ocular/0/2569_left.jpg              True
1     /content/drive/MyDrive/ocular/0/2570_left.jpg              True
3     /content/drive/MyDrive/ocular/0/2572_left.jpg              True
4     /content/drive/MyDrive/ocular/0/2573_left.jpg              True
5     /content/drive/MyDrive/ocular/0/2574_left.jpg              True
...                                             ...               ...
3418  /content/drive/MyDrive/ocular/1/2010_left.jpg              True
3419  /content/drive/MyDrive/ocular/1/2020_left.jpg              True
3420  /content/drive/MyDrive/ocular/1/2030_left.jpg              True
3421  /content/drive/MyDrive/ocular/1/2041_left.jpg              True
3423  /content/drive/MyDrive/ocular/1/2074_left.jpg              True

[3042 rows x 2 columns]

In [ ]:
len(glob.glob("/content/drive/MyDrive/ocular_clean/0/*.*"))

2780

In [ ]:
len(glob.glob("/content/drive/MyDrive/ocular_clean/1/*.*"))

262

In [ ]:
def get_disk(image):
    image = cv2.imread(image)
    print (image)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.bilateralFilter(gray,9,75,75)
    median=cv2.medianBlur(blur, 5)

    # threshold the image to reveal light regions in the
    # blurred image
    thresh = cv2.threshold(median, 155, 255, cv2.THRESH_BINARY)[1]
    # perform a series of erosions and dilations to remove
    # any small blobs of noise from the thresholded image
    thresh = cv2.erode(thresh, None, iterations=2)
    thresh = cv2.dilate(thresh, None, iterations=4)

    # perform a connected component analysis on the thresholded
    # image, then initialize a mask to store only the "large"
    # components
    labels = measure.label(thresh, connectivity=2, background=0)
    mask = np.zeros(thresh.shape, dtype="uint8")

    # loop over the unique components
    for label in np.unique(labels):
      # if this is the background label, ignore it
      if label == 0:
        continue

      # otherwise, construct the label mask and count the
      # number of pixels 
      labelMask = np.zeros(thresh.shape, dtype="uint8")
      labelMask[labels == label] = 255
      numPixels = cv2.countNonZero(labelMask)

      # if the number of pixels in the component is sufficiently
      # large, then add it to our mask of "large blobs"
      if numPixels >500:
        mask = cv2.add(mask, labelMask)

    # find the contours in the mask, then sort them from left to
    # right
    cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
      cv2.CHAIN_APPROX_SIMPLE)
    cnts = imutils.grab_contours(cnts)
    # print(contours.sort_contours(cnts))
    cnts = contours.sort_contours(cnts)[0]
    # print (cnts)
    # loop over the contours
    for (i, c) in enumerate(cnts):
        ellipse = cv2.fitEllipse(c)
        (x, y, w, h) = cv2.boundingRect(c)
        break
      # draw the bright spot on the image

    padding = 100
    image = image[y-padding:y+h+padding, x-padding:x+w+padding]
    return image

In [ ]:
get_disk("/content/drive/MyDrive/ocular_clean/0/1005_right.jpg")

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


array([[[ 62, 130, 195],
        [ 60, 131, 195],
        [ 60, 131, 195],
        ...,
        [ 51, 110, 172],
        [ 51, 110, 172],
        [ 50, 111, 173]],

       [[ 61, 129, 194],
        [ 60, 131, 195],
        [ 60, 131, 195],
        ...,
        [ 51, 110, 172],
        [ 51, 110, 172],
        [ 49, 110, 172]],

       [[ 60, 128, 193],
        [ 59, 130, 194],
        [ 59, 130, 194],
        ...,
        [ 51, 110, 172],
        [ 51, 110, 172],
        [ 51, 110, 172]],

       ...,

       [[ 55, 126, 193],
        [ 51, 127, 193],
        [ 53, 127, 193],
        ...,
        [ 61, 115, 176],
        [ 61, 115, 176],
        [ 60, 114, 174]],

       [[ 56, 126, 193],
        [ 51, 127, 193],
        [ 53, 127, 193],
        ...,
        [ 61, 115, 176],
        [ 61, 115, 176],
        [ 62, 116, 176]],

       [[ 54, 124, 191],
        [ 49, 125, 191],
        [ 51, 125, 191],
        ...,
        [ 60, 114, 175],
        [ 62, 116, 177],
        [ 63, 117, 177]]